<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'GUIDO CACERES',
  'description' => 'Modificacion de reuniones',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'reuniones',
  'published_date' => '2019-04-13 13:47:57',
  'type' => 'module',
  'version' => 1555163278,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'reuniones',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.reuniones.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_ES.reuniones.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/language/es_ES.lang.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
  ),
  'custom_fields' => 
  array (
    'Meetingsjjwg_maps_address_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Meetings',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-02-08 21:01:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Meetingsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Meetings',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-02-08 21:01:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Meetingsjjwg_maps_lat_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => '',
      'help' => 'Latitude',
      'module' => 'Meetings',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2019-02-08 21:01:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Meetingsjjwg_maps_lng_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => '',
      'help' => 'Longitude',
      'module' => 'Meetings',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => '0.00000000',
      'date_modified' => '2019-02-08 21:01:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Meetingstipo_asunto_c' => 
    array (
      'id' => 'Meetingstipo_asunto_c',
      'name' => 'tipo_asunto_c',
      'label' => 'LBL_TIPO_ASUNTO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Meetings',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => '',
      'date_modified' => '2019-04-13 13:40:07',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'asunto_reunion_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Meetings/metadata/detailviewdefs.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Meetings/metadata/detailviewdefs.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/editviewdefs.php',
      'to' => 'custom/modules/Meetings/metadata/editviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Meetings/metadata/editviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Meetings/metadata/listviewdefs.php',
      'to' => 'custom/modules/Meetings/metadata/listviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_lng_c.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_lat_c.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_geocode_status_c.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_jjwg_maps_address_c.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_tipo_asunto_c.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_tipo_asunto_c.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/Extension/modules/Meetings/Ext/Vardefs/sugarfield_name.php',
      'to' => 'custom/Extension/modules/Meetings/Ext/Vardefs/sugarfield_name.php',
    ),
  ),
);